---
title: "miRNA Analysis"
author: "Sean Davis"
date: "`r Sys.Date()`"
output: html_document
---

```{r init}
library(knitr)
library(Biobase)
library(survival)
library(DT)
opts_chunk$set(cache=TRUE,warning=FALSE,message=FALSE)
```

```{r loadPackage}
#require(TARGOS)
options('DCC' = '/data/CCRBioinfo/projects/TargetOsteosarcoma/OtherData/DCC')
mirna = getmiRNA()
```

## Metastasis at presentation

```{r metastasisAtPresentation}
library(limma)
met = factor(ifelse(pData(mirna)$Disease.at.diagnosis=='Metastatic',"Yes","No"))
dm = model.matrix(~0 + met)
cm = makeContrasts(metYes-metNo,levels=dm)
fit1 = lmFit(exprs(mirna),dm)
fit2 = contrasts.fit(fit1,cm)
fit3 = eBayes(fit2)
```

```{r reportMets,cache=FALSE}
datatable(topTable(fit3,number=Inf))
```

## Survival analysis

```{r coxph}
coxphPval = sapply(seq_len(nrow(mirna)),function(i) {
  return(summary(with(pData(mirna),coxph(Surv(Overall.Survival.Time.in.Days,as.numeric(Vital.Status.=='Dead')) ~ exprs(mirna)[i,])))$waldtest['pvalue'])
  })
coxphFDR = p.adjust(coxphPval)
```


```{r results,cache=FALSE}
library(DT)
df = data.frame(mirna = featureNames(mirna),
                     pval = coxphPval, 
                     fdr = coxphFDR)
datatable(df[!is.na(df$fdr),])
```


